services:
  - type: web
    name: cricket-club-api
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn cricket_club.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: "club-management-system-tegz.onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://club-management-system-tegz.onrender.com"
      - key: DJANGO_CORS_ALLOWED_ORIGINS
        value: "https://club-management-system-tegz.onrender.com"
      - key: DJANGO_CORS_ALLOW_ALL_ORIGINS
        value: "true"
      - key: DATABASE_URL
        value: "postgresql://kk11:5Rla8UGvbCxTtVTaGEj99fnscCTProNJ@dpg-d6a2kk6mcj7s7391pc4g-a/kk11"
databases:
  - name: kk11
    plan: free
